### ISSUE TITLE
error @r11.0.2_b

### ISSUE THREAD

**Issue by srbaby** [deluge411/godlike_critsounds#1]
**My Locale is "zhCN", the addon can't work, here is the error:**
> 
> 
>
5x Godlike/Core.lua:97: attempt to concatenate global 'GL_TEXT_OPT_SETAUTO' (a nil value)
[string "@Godlike/Core.lua"]:97: in main chunk

Locals:
AC = <table> {
}
ACD = <table> {
 tooltip = AceConfigDialogTooltip {
 }
 BlizOptions = <table> {
 }
 popup = Frame {
 }
 OpenFrames = <table> {
 }
 Status = <table> {
 }
 frame = Frame {
 }
}
THIS_VERSION = "11.0.0"
defaults = <table> {
 profile = <table> {
 }
}
(*temporary) = <table> {
 type = "group"
 name = "Godlike Settings 11.0.0"
 handler = <table> {
 }
}
(*temporary) = <table> {
 isAuto = <table> {
 }
 isSoundEnabled = <table> {
 }
 header = <table> {
 }
 isEnabled = <table> {
 }
 isMessageEnabled = <table> {
 }
}
(*temporary) = <table> {
 type = "range"
 order = 6
}
(*temporary) = nil
(*temporary) = " % Auto Critical Value"
(*temporary) = "attempt to concatenate global 'GL_TEXT_OPT_SETAUTO' (a nil value)"

**Comment by deluge411** [comment]
> **My Locale is "zhCN", the addon can't work, here is the error:**
> 
> > 
> 
> 5x Godlike/Core.lua:97: attempt to concatenate global 'GL_TEXT_OPT_SETAUTO' (a nil value) [string "@Godlike/Core.lua"]:97: in main chunk
> 
> Locals: AC =
> {
> }
> ACD =
> {
> tooltip = AceConfigDialogTooltip {
> }
> BlizOptions =
> {
> }
> popup = Frame {
> }
> OpenFrames =
> {
> }
> Status =
> {
> }
> frame = Frame {
> }
> }
> THIS_VERSION = "11.0.0"
> defaults =
> {
> profile =
> {
> }
> }
> (*temporary) =
> {
> type = "group"
> name = "Godlike Settings 11.0.0"
> handler =
> {
> }
> }
> (*temporary) =
> {
> isAuto =
> {
> }
> isSoundEnabled =
> {
> }
> header =
> {
> }
> isEnabled =
> {
> }
> isMessageEnabled =
> {
> }
> }
> (*temporary) =
> {
> type = "range"
> order = 6
> }
> (*temporary) = nil
> (*temporary) = " % Auto Critical Value"
> (*temporary) = "attempt to concatenate global 'GL_TEXT_OPT_SETAUTO' (a nil value)"

I don't think godlike supports chinese locale, but let me see if I can push a fix to resolve your issue. Can you tell me what version of WoW this is in? Retail? Classic?

**Comment by deluge411** [comment]
Try now, I added a zhCN locale file but it is in english just so it doesn't give you the error. Let me know if it works since I can't try it so I can close this issue.

**Comment by srbaby** [comment]
Awesome! The plugin is working perfectly. I've used it for a while and basically understand its operating logic; it's quite interesting. However, I'm concerned that in specific scenarios, such as during vulnerability or when massive critical hits occur, it might affect the automatic critical hits. I'll test it out for a while first. Also, I've made a simple translation of the zhCN file, which you can include in future updates. Thank you for creating this plugin.

[localization_zhCN.zip](https://github.com/user-attachments/files/16828715/localization_zhCN.zip)
